# Generated by Django 5.0.4 on 2024-04-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.BinaryField()),
                ('BPMeds', models.BinaryField(default=0)),
                ('prevalentStroke', models.BinaryField(default=0)),
                ('prevalentHyp', models.BinaryField(default=0)),
                ('diabetes', models.BinaryField(default=0)),
                ('log_cigsPerDay', models.IntegerField(default=0)),
                ('log_totChol', models.FloatField()),
                ('log_diaBP', models.FloatField()),
                ('log_BMI', models.FloatField()),
                ('log_heartRate', models.FloatField()),
                ('log_glucose', models.FloatField()),
                ('log_age', models.IntegerField()),
            ],
        ),
    ]
