# Generated by Django 5.0.4 on 2024-04-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartpredict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='BPMeds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='diabetes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='male',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='prevalentHyp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='prevalentStroke',
            field=models.IntegerField(default=0),
        ),
    ]
